// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKPX_TTNfWNL0cHOHtd3bAicazUAFvb-U',
    appId: '1:348048061983:web:701a77c7acd11dd9ec872a',
    messagingSenderId: '348048061983',
    projectId: 'threads-clone-f8cd1',
    authDomain: 'threads-clone-f8cd1.firebaseapp.com',
    storageBucket: 'threads-clone-f8cd1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSfLPENJrpK6RzuZHgd_6S5bGaqWHZvFc',
    appId: '1:348048061983:android:3a7b414bbb395955ec872a',
    messagingSenderId: '348048061983',
    projectId: 'threads-clone-f8cd1',
    storageBucket: 'threads-clone-f8cd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEiXSEOAueIx2ARGUxAjdWltApADYippE',
    appId: '1:348048061983:ios:da69a57703b008bdec872a',
    messagingSenderId: '348048061983',
    projectId: 'threads-clone-f8cd1',
    storageBucket: 'threads-clone-f8cd1.firebasestorage.app',
    iosBundleId: 'com.example.threadsClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEiXSEOAueIx2ARGUxAjdWltApADYippE',
    appId: '1:348048061983:ios:da69a57703b008bdec872a',
    messagingSenderId: '348048061983',
    projectId: 'threads-clone-f8cd1',
    storageBucket: 'threads-clone-f8cd1.firebasestorage.app',
    iosBundleId: 'com.example.threadsClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKPX_TTNfWNL0cHOHtd3bAicazUAFvb-U',
    appId: '1:348048061983:web:1770d89498602f94ec872a',
    messagingSenderId: '348048061983',
    projectId: 'threads-clone-f8cd1',
    authDomain: 'threads-clone-f8cd1.firebaseapp.com',
    storageBucket: 'threads-clone-f8cd1.firebasestorage.app',
  );
}
